language: ruby

before_install:
   - wget https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.1.0-1_amd64.deb
   - sudo dpkg -i https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.1.0-1_amd64.deb
   - bundle install

gemfile:
   - test/support/Gemfile

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0

script: 
  - bundle exec rake foodcritic
  - bundle exec rake test
