language: ruby

before_install:
  - sudo apt-get -y install vagrant

gemfile:
   - test/support/Gemfile

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0

script: 
  - bundle exec rake foodcritic
  - bundle exec rake test
